---
name: Update Action on JSON Change

on:
  push:
    paths:
      - 'cfn/**.json'
      - '.github/workflows/cloudformation.yml'

jobs:
  update-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List changed JSON files
        id: list-json-changes
        run: |
          before_commit=${{ github.event.before }}
          after_commit=${{ github.sha }}
          echo "Before commit: $before_commit"
          echo "After commit: $after_commit"
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'cfn/**/*.json')
          echo "::set-output name=changed_files::${changed_files}"
        shell: bash

      - name: Extract app names and trigger action
        run: |
          chmod +x update_cfn.sh
          ./update_cfn.sh "${{ steps.list-json-changes.outputs.changed_files }}"
        shell: bash
...