---
name: Update Action on JSON Change

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cfn/**.json'
      - '.github/workflows/*.*'

jobs:
  cfn-lint:
    name: CFN Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint cfn/**/*.json -a tests/cfn-lint/rules

  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest tests/

  black-fmt:
    name: Python Black Linting
    runs-on: ubuntu-latest

    steps:
      - name: Python Black Linting
        run: |
          pip install black
          black --check --diff .

  update-action:
    needs: [cfn-lint, black-fmt, pytest]
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List changed JSON files
        id: list-json-changes
        run: |
          before_commit=${{ github.event.before }}
          after_commit=${{ github.sha }}
          echo "Before commit: $before_commit"
          echo "After commit: $after_commit"
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'cfn/**/*.json')
          echo "${changed_files}" >> ./.github/workflows/changed_files
          cat ./.github/workflows/changed_files
        shell: bash

      - name: Extract app names and trigger action
        run: |
          chmod +x ./.github/workflows/update_cfn.sh
          ./.github/workflows/update_cfn.sh
        shell: bash
...