---
name: Update Action on JSON Change

on:
  push:
    paths:
      - 'cfn/**.json'
      - '.github/workflows/cloudformation.yml'

jobs:
  update-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List changed JSON files
        id: list-json-changes
        run: |
          before_commit=${{ github.event.before }}
          after_commit=${{ github.sha }}
          echo "Before commit: $before_commit"
          echo "After commit: $after_commit"
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'cfn/**/*.json')
          echo "::set-output name=changed_files::${changed_files}"
        shell: bash
        with:
          fetch-depth: 0

      - name: Extract app names and trigger action
        run: |
          for json_file in ${{ steps.list-json-changes.outputs.changed_files }}; do
            app_name=$(basename $(dirname $json_file))
            echo "${app_name}" has changed.
            # Perform your desired action here using $app_name
          done
        shell: bash
...